image: ubuntu
before_script:
  # setup ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # install rsync
  - apt-get update -qq && apt-get install -y -qq rsync

stages:
  - deploy

deploy:
  stage: deploy
  script:
  # deploy artifacts
    - tar -cvzf artifacts.tar.gz css js
    - rsync -r artifacts.tar.gz deploy.sh $SSH_LOGIN:$REMOTE_PATH/test/
    - ssh $SSH_LOGIN chmod +x $REMOTE_PATH/test/deploy.sh;
    - ssh $SSH_LOGIN $REMOTE_PATH/test/deploy.sh;
