image: ubuntu
before_script:
  # setup ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # install rsync
  - apt-get update -qq && apt-get install -y -qq rsync

stages:
  - deploy

deploy:
  stage: deploy
  script:
  # deploy artifacts
    - tar -cvzf artifacts.tar.gz css js
    - rsync -r artifacts.tar.gz $SSH_LOGIN:$REMOTE_PATH/PROJECT_KEY/
    - mkdir $REMOTE_PATH/PROJECT_KEY/release;
    - tar -xvzf $REMOTE_PATH/PROJECT_KEY/artifacts.tar.gz --directory $REMOTE_PATH/PROJECT_KEY/release
    - rm $REMOTE_PATH/PROJECT_KEY/backup -Rf;
    - mv $REMOTE_PATH/PROJECT_KEY/master ./backup;
    - mv $REMOTE_PATH/PROJECT_KEY/release ./master;
    - rm $REMOTE_PATH/PROJECT_KEY/artifacts.tar.gz